language: cpp

compiler:
  - gcc

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55/cmake-3.x
    packages:
    - gcc-8
    - g++-8
    - gcc-8-multilib
    - g++-8-multilib
    - libc6-dev-i386
    - libc6-i386
    - linux-libc-dev:i386
    - libgtest-dev
    - libboost-dev
    - cmake
  
before_install:
  - echo `getconf _NPROCESSORS_ONLN`
  - lsb_release -c
  - lsb_release -r
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
before_script:
  - mkdir gtest_build
  - cd gtest_build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON /usr/src/gtest/
  - make -j$((2 * `getconf _NPROCESSORS_ONLN`))
  - sudo mv libg* /usr/lib/
  - cd -
  - cmake --version
  - cmake .
script: 
  - make -j$((2 * `getconf _NPROCESSORS_ONLN`))
  
sudo: required
dist: trusty
